### PR TITLE
Simplify and fix solaris endian.h macros

### LINKED ISSUE #898: solaris_ci regression
I've added `gmake -j2 check || (cat tests/test-suite.log && exit 1)` 
(probably, I'll add something like that in PR)

build link:
https://github.com/chipitsine/portable/actions/runs/5879700788/job/15944351160#step:4:18195

```
 libressl 3.8.1: tests/test-suite.log
  ==========================================
  # TOTAL: 124
  # PASS:  117
  # SKIP:  0
  # XFAIL: 0
  # FAIL:  7
  # XPASS: 0
  # ERROR: 0
  .. contents:: :depth: 2
  FAIL: aeadtest.sh
  =================
  ./aeadtest.sh: line 7: 7289: Memory fault(coredump)
  ../test-driver: line 112: 7287: Memory fault(coredump)
  FAIL aeadtest.sh (exit status: 267)
  FAIL: apitest
  =============
  == Testing SSL_get_peer_cert_chain()... ==
  ../test-driver: line 112: 7297: Memory fault(coredump)
  FAIL apitest (exit status: 267)
  FAIL: gcm128test
  ================
  ../test-driver: line 112: 7566: Memory fault(coredump)
  FAIL gcm128test (exit status: 267)
  FAIL: signertest
  ================
  ../test-driver: line 112: 7687: Memory fault(coredump)
  FAIL signertest (exit status: 267)
  FAIL: ssl_get_shared_ciphers
  ============================
  ../test-driver: line 112: 7699: Memory fault(coredump)
  FAIL ssl_get_shared_ciphers (exit status: 267)
  FAIL: ssltest.sh
  ================
  WARNING: can't open config file: /usr/local/etc/ssl/openssl.cnf
  LibreSSL 3.8.1
  WARNING: can't open config file: /usr/local/etc/ssl/openssl.cnf
  test sslv2/sslv3
  ./testssl: line 21: 7731: Memory fault(coredump)
  FAIL ssltest.sh (exit status: 1)
  FAIL: tlstest.sh
  ================
  ./tlstest.sh: line 13: 7855: Memory fault(coredump)
  ../test-driver: line 112: 7854: Memory fault(coredump)
  FAIL tlstest.sh (exit status: 267)
```

### PR DESCRIPTION
**Pull request by botovq**
Fixes #898

### CODE REVIEW

**Comment by botovq** [comment]
The issue is that the `{B,L}E_IN*()` macros take a pointer argument that they dereference. This will of course result in a bad memory access. That issue was previously hidden by the assembler implementations for the sha digests.

I'll merge this PR once the solaris CI on my repo completes and succeeds.

Many thanks to @chipitsine for the invaluable help in tracking this down.

**Comment by busterb** [comment]
Thanks @botovq. In an ideal world, this shouldn't have compiled, but it did!

**Comment by botovq** [comment]
On Fri, Aug 18, 2023 at 02:21:46AM -0700, Brent Cook wrote:
> Thanks @botovq. In an ideal world, this shouldn't have compiled, but it did!

Well, in that ideal world they would not make extra sure the compiler
won't complain no matter what you stuff into this macro :)

#define BE_IN64(x) htonll(*((uint64_t *)(void *)(x)))

I heard rumors that someone will add regress coverage for endian.h...

**Comment by chipitsine** [comment]
I could not find easy way how to run regress on linux, for example.
not sure about solaris as well

**Comment by chipitsine** [comment]
by "regress" do you mean https://github.com/libressl/openbsd/tree/master/src/regress ?

**Comment by botovq** [comment]
On Fri, Aug 18, 2023 at 04:14:02AM -0700, Ilya Shipitsin wrote:
> by "regress" do you mean https://github.com/libressl/openbsd/tree/master/src/regress ?

Not really. What I meant is that ideally we'd have good regress coverage
for our compat layer itself. This way we can identify such problems
right when adding a platform to our CI.

The problem here was nasty and well hidden because until very recently
the relevant endian.h compat macros weren't actually used on Solaris
because of asm implementations for SHA-2.

Regarding that src/regress directory: the tests and artefacts are copied
to `portable/tests` by `./update.sh`. We have the portable Makefile and
scripting glue in https://github.com/libressl/portable/tree/master/tests

What isn't hooked to `make check` and `ninja test` is omitted for a
reason, usually because it has external dependencies that we can't
bundle for licensing reasons or things that we don't want to require for
ordinary portable builds (such as Go, Python, or Ruby, the Wycheproof
vectors or tlsfuzzer).

**Comment by chipitsine** [comment]
I thought that "make check" is somewhat belonging to portable, while "src/regress" is openbsd specific. I have to have a deeper look.

interesting, that I do not see https://github.com/libressl/openbsd/tree/master/src/regress/lib/libssl/quic running on portable (as well as few other tests)

**Comment by botovq** [comment]
On Fri, Aug 18, 2023 at 06:39:52AM -0700, Ilya Shipitsin wrote:
> I thought that "make check" is somewhat belonging to portable, while "src/regress" is openbsd specific. I have to have a deeper look.

That's correct.

> interesting, that I do not see https://github.com/libressl/openbsd/tree/master/src/regress/lib/libssl/quic running on portable (as well as few other tests)

It is well possible that things are overlooked. Regarding quic:

 85/124 Test  #85: quictest .........................   Passed    0.01 sec

**Pull request merged**
