### PR TITLE
remove additional endbr64 patch, add tests for macos-11

### LINKED ISSUE #933: aes/aesni-macosx-x86_64.S:890:2: error: invalid instruction mnemonic 'endbr64'
Same error as the resolved https://github.com/libressl/portable/issues/866 but now in another file:

> Making check in openssl
echo "generating opensslconf.h ..."
generating opensslconf.h ...
cp ../../include/arch/amd64/opensslconf.h opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
make[3]: Nothing to be done for `check-am'.
make[2]: Nothing to be done for `check-am'.
Making check in crypto
echo "generating crypto_portable.sym ..."
generating crypto_portable.sym ...
cp ../crypto/crypto.sym crypto_portable.sym
chmod u+w crypto_portable.sym
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
  CPPAS    aes/libcrypto_la-aes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-bsaes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-vpaes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-aesni-macosx-x86_64.lo
aes/aesni-macosx-x86_64.S:890:2: error: invalid instruction mnemonic 'endbr64'
 endbr64
 ^~~~~~~
make[2]: *** [aes/libcrypto_la-aesni-macosx-x86_64.lo] Error 1
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1
start make...
Making all in include
Making all in openssl
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[3]: Nothing to be done for `all-am'.
make[2]: Nothing to be done for `all-am'.
Making all in crypto
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CPPAS    aes/libcrypto_la-aesni-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-aesni-sha1-macosx-x86_64.lo
aes/aesni-macosx-x86_64.S:890:2: error: invalid instruction mnemonic 'endbr64'
 endbr64
 ^~~~~~~
make[2]: *** [aes/libcrypto_la-aesni-macosx-x86_64.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

Last successful build was 2023-10-21.

### PR DESCRIPTION
**Pull request by busterb**
Fixes #933 , revert one additional patch when targeting macos/windows

### CODE REVIEW

**Review by joshuasing — APPROVED** [review]

**Comment by botovq** [comment]
On Thu, Nov 09, 2023 at 09:28:58PM -0800, Joshua Sing wrote:
> @joshuasing approved this pull request.

I haven't yet had a chance to look at the details of this failure
because github helpfully hides them when not logged in, but what I'm
most concerned about is that I didn't get notified of the test failure.

**Comment by busterb** [comment]
It wasn't that there was a failure we didn't get notified; more that there was no failure at all. The issue seemed to only occur if you have an older compiler. All of my local machines and the Github images were new enough that they all worked without showing a problem.

I'm not 100% sure that enabling the macos-11 image in this PR is enough, since it might have a newer compiler too compared to what someone using Apple's Xcode would have: https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md

**Comment by busterb** [comment]
Yep, it's not enough; this line was intended to have failed, but didn't: https://github.com/libressl/portable/actions/runs/6822970903/job/18555981286#step:4:703

**Comment by busterb** [comment]
Examining some of the other build results, it appears that the architecture attribute is not doing anything either; the arm64 target is still building x86_64: https://github.com/libressl/portable/actions/runs/6822970903/job/18555980718#step:4:686

**Comment by botovq** [comment]
Yes, sorry, I accidentally replied to the wrong thread. This was about #944.

**Comment by botovq** [comment]
Apologies for the mess.

**Pull request merged**
