### PR TITLE
Run tests for macos-14 on arm64

### PR DESCRIPTION
**Pull request by nak3**
macos-12 and macos-13 fails `make test` on arm64 but macos-14 can pass. 
Hence this patch enables it on github action.

### CODE REVIEW

**Comment by botovq** [comment]
Thanks. What fails on macos-12 and macos-13?

I'd like to repeat my concern: macos is by far the slowest of the CI.
It's annoying to wait for it. Can it reasonably be split? Perhaps if 12
and 13 aren't fixable on the M1, we could have a legacy macos CI and a
macos 14 CI?

**Comment by nak3** [comment]
> What fails on macos-12 and macos-13?

The error produces `[Unknown system error -86]`. Unfortunately macOS does not provide much the hint.

log - https://github.com/nak3/portable/actions/runs/8373109169/job/22925506730

```
2024-03-21T10:11:30.9340490Z + make test
2024-03-21T10:11:30.9584630Z Running tests...
2024-03-21T10:11:31.0164090Z Test project /Users/runner/work/portable/portable/libressl-3.9.0/build-static
2024-03-21T10:11:31.0217920Z         Start   1: aeadtest
2024-03-21T10:11:31.0269460Z   1/125 Test   #1: aeadtest .........................***Failed    0.00 sec
2024-03-21T10:11:31.0272950Z         Start   2: aes_test
2024-03-21T10:11:31.0276700Z Process not started
2024-03-21T10:11:31.0277940Z  /Users/runner/work/portable/portable/libressl-3.9.0/build-static/tests/aes_test
2024-03-21T10:11:31.0278880Z [Unknown system error -86]
2024-03-21T10:11:31.0279490Z   2/125 Test   #2: aes_test .........................***Not Run   0.00 sec
2024-03-21T10:11:31.0280740Z         Start   3: aes_wrap
2024-03-21T10:11:31.0284970Z Process not started
2024-03-21T10:11:31.0286040Z  /Users/runner/work/portable/portable/libressl-3.9.0/build-static/tests/aes_wrap
2024-03-21T10:11:31.0286960Z [Unknown system error -86]
...
```

> I'd like to repeat my concern: macos is by far the slowest of the CI.
> It's annoying to wait for it. Can it reasonably be split? Perhaps if 12
> and 13 aren't fixable on the M1, we could have a legacy macos CI and a
> macos 14 CI?

Sure, I split the job into two files.

**Comment by nak3** [comment]
@joshuasing Could you please take a look? (I found that you were requested for the review.)

**Review by joshuasing — CHANGES_REQUESTED** [review]
Would you mind undoing moving macos-13 and macos-12 to a separate workflow?
I don't believe this change will make much of a difference in terms of run time.

**Comment by nak3** [comment]
Alright, updated. Thanks.

**Review by joshuasing — APPROVED** [review]

**Pull request merged**
