### PR TITLE
ci: clean up Windows workflow

### PR DESCRIPTION
**Pull request by joshuasing**
Clean up existing `windows` GitHub Actions workflow.

Changes:
- Move `windows_test.yml` to `windows.yml`
- Restrict token permissions to `contents: read`
- Pin `actions/checkout` to `v4`
- Update `actions/upload-artifact` to `v4`
- Overall tidy up
- Use more common naming conventions
- Add schedule to run weekly
- Add Windows workflow badge to `README.md` file

### CODE REVIEW

**Comment by botovq** [comment]
I should have caught this earlier: for cmake builds you can run
./update.sh instead of ./autogen.sh and there should be no need
for autotools/automake/libtool.

**Comment by joshuasing** [comment]
> I should have caught this earlier: for cmake builds you can run ./update.sh instead of ./autogen.sh and there should be no need for autotools/automake/libtool.

Ah, okay. I've pushed a commit to make those changes.

**Comment by botovq** [comment]
> Ah, okay. I've pushed a commit to make those changes.

Is autoconf still needed?

**Comment by joshuasing** [comment]
> Ah, okay. I've pushed a commit to make those changes.
> Is autoconf still needed?

I do not know. I will try removing it and see if it still builds.

The previous commit seems to have reduced the total workflow duration from 14-27 minutes to 7 minutes.

**Comment by botovq** [comment]
Not sure what you are signalling with assigning this to yourself.

Should I merge if green or is there more you want to do here?

**Comment by joshuasing** [comment]
> Not sure what you are signalling with assigning this to yourself. Should I merge if green or is there more you want to do here?

Sorry for the confusion, in another project I often use the pull request assignees to show who is working on the pull request, and did so here out of habit. This should be good to merge now.

**Pull request merged**
