### PR TITLE
cmake: disable default NDEBUG differently

### PR DESCRIPTION
**Pull request by vszakats**
This method allows to set it via custom flags.

### CODE REVIEW

**Comment by vszakats** [comment]
`-UNDEBUG` seems to hide valid build issues at compile-time, so an possibly
better solution would be to just delete the logic touching this macro and leaving
it to the CMake default.

**Comment by busterb** [comment]
Thanks. I was just looking at build logs for another diff, being slightly annoyed there wasn't a better way to override NDEBUG without a bunch of warnings.

**Comment by vszakats** [comment]
Is there something to do, or any pending concern with this PR to get merged?

**Comment by vszakats** [comment]
This patch was merged, yet surprisingly, it's missing from master and both from 3.8.3 and 3.9.0.

Was it intended?

**Comment by busterb** [comment]
I wonder if this got merged to the github mirror only, then was overwritten when we synced up. I only see it referred to in the PR branch in the actual source tree, and there wasn't a revert that I can see.

**Comment by vszakats** [comment]
Yes, that's possible.

I've opened #1016 to try one more time. Or the previous patch 
can also be re-applied, whichever is more convenient.

**Pull request merged**
