### PR TITLE
Revert COVERITY_SCAN_PROJECT_NAME change in Coverity workflow

### PR DESCRIPTION
**Pull request by joshuasing**
This pull request reverts `COVERITY_SCAN_PROJECT_NAME` being changed to `libressl/portable` in the Coverity workflow.
The last workflow run failed due to Coverity not finding the project, as it still has the old `libressl-portable/portable` name.

This fix may work, as long as Coverity follows the GitHub redirect, however if it doesn't, the Coverity project might need to be re-created.

### CODE REVIEW

**Comment by botovq** [comment]
Try it.

**Comment by botovq** [comment]
On Wed, Jan 11, 2023 at 11:29:06PM -0800, Joshua Sing wrote:
> @joshuasing requested your review on: libressl/portable#812 Revert COVERITY_SCAN_PROJECT_NAME change in Coverity workflow.

But what is .idea/workspace.xml?

Could you please not use 'request review'? I don't need two mails to
look at a PR from you.

**Comment by joshuasing** [comment]
> But what is .idea/workspace.xml?
`.idea/` is a directory for project configurations used by JetBrains IDEs, and I forgot to gitignore/remove before making a commit.

> Could you please not use 'request review'? I don't need two mails to look at a PR from you.
Yes, sorry, I was unaware that was the case.

**Comment by botovq** [comment]
This looks better now. There's a missing newline at the end of
.gitignore.

**Pull request merged**
