### PR TITLE
Hook ML-KEM related tests

### PR DESCRIPTION
**Pull request by nak3**
This patch adds ML-KEM related tests.

### CODE REVIEW

**Comment by nak3** [comment]
Linux's and emscripten's ASAN will be failed. These need to be fixed in some main codes discussed in this thread https://marc.info/?l=openbsd-tech&m=173441751232320&w=2

**Comment by botovq** [comment]
Great, thanks! This pretty much matches what I had planned to do but didn't get around to doing yet (in particular testing with ASAN) yet. I have synced your fixes from tech@, so please rebase this PR on top of master.

**Comment by botovq** [comment]
Ah, apparently there's no need. Retriggering the test seems to pick up the fixed source. I'll merge once all is green.

Many thanks!

**Comment by nak3** [comment]
Yes, thank you as well for your prompt response!

**Pull request merged**
