### PR TITLE
Add tests for macos-14

### PR DESCRIPTION
**Pull request by nak3**
This patch adds test for macos-14.

### CODE REVIEW

**Comment by nak3** [comment]
Note - macos-14 needs to install libtool otherwise it got an error as https://github.com/nak3/portable/actions/runs/8323041680/job/22771906307

**Review by joshuasing — APPROVED** [review]
Thanks!

Related information that could become useful later:
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

**Comment by botovq** [comment]
I'm not super keen on making the macos CI  even slower than it already is. Can we perhaps split this job into two that run in parallel or drop the oldest?

**Comment by nak3** [comment]
Alright, I dropped the oldest (macos-11).

**Comment by botovq** [comment]
Thanks. @joshuasing any opinion on this?

**Comment by joshuasing** [comment]
> Thanks. @joshuasing any opinion on this?

@botovq I think this is a good change, and I have approved the pull request.

**Comment by botovq** [comment]
@joshuasing You approved before macos11 was dropped and I can't see a renewal of the approval in the timeline, hence my question.

**Pull request merged**
