### PR TITLE
Fix MinGW-w64 assembler check in CMake always failing

### PR DESCRIPTION
**Pull request by rfl890**
On windows, CMAKE_SYSTEM_PROCESSOR will never be "x86_64", only "AMD64". This is accounted for by setting the HOST_X86_64 variable, but for some reason it's not used at all. This fixes that issue.

### CODE REVIEW

**Comment by botovq** [comment]
Thanks. This looks right to me. The CI failure is unrelated and was fixed in HEAD. Could you please rebase and push again to see if it's all good now?

**Comment by rfl890** [comment]
It seems https://github.com/libressl/openbsd/commit/3d1118fa05274d1f3789ca743e76aba59045acf7 is the offending commit here

**Comment by botovq** [comment]
Yeah, that or the previous one. looking.

**Comment by botovq** [comment]
Thanks. Apologies for these hiccups.

**Pull request merged**
